# These services should not be restarted after the program runs
services:
  gateway:
    build:
      context: ./services/cognibrew-microservices/cognibrew-cloud-api-gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8001:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - PROJECT_NAME=CogniBrew Cloud API Gateway
      - DEBUG=false
      - LOG_LEVEL=INFO
      - API_PREFIX_STR=/api/v1
      - CATALOG_SERVICE_URL=http://catalog:8000
      - FEEDBACK_SERVICE_URL=http://feedback-service:8080
      - NOTIFICATION_SERVICE_URL=http://notification-service:8080
      - USER_MANAGEMENT_SERVICE_URL=http://user-management-service:5001
      - JWT_SECRET_KEY=5hSUiLqYu5jnTy2EG4JOLLCOTfgjzQ3NAeSCEPPyhO2ECLOTZSy2jX16uRrAOlSk5kqP6NLoa5X8fFKwAOuvGLhqBKbrMI9l2C2WFLKum8nfjolsynuTDEItZn7xWkaw41flM9OLFWuXhsoH2WWu7kETs6l1YIj0rjxqMU0YU7QSRDjlhh8Mek7oICFa8FhvFchPrzUwXAcG6krjkrujUmIjTFB2Pb1jytVZjTuyWpL3qmi51p57sR2OPeH67M3NHPKEypZoviC79iDVbA9kwf4JqJyUsaDhgWUJRD3l8CPPlsasiDHFN4jKpBj9CJzoMRAZ935xKM4r9RHRVhib96fmW4dZCrsD3fzQ95TCDW6bi39f1traglvzjfC919ReBQk57ZqEhViKpKm0uiBB1pbrKifs9r9LoZamE7FFZAYsbyvTJihg4CpKIRgoDfV28Zy4bv9zstWxCzoPhlae529pGXA6AorUwpbdBTV9OZRS9xyHFHWMAHTuLmiSeuzr
      - JWT_ISSUER=semls-app-group
      - JWT_AUDIENCE=semls-app-audience
      - JWT_ALGORITHMS=HS256
      - HTTP_TIMEOUT=30.0
    depends_on:
      - catalog
      - recommendation
    networks:
      - cognibrew
    restart: always

  cognibrew-rabbitmq:
    image: rabbitmq:4.2.5-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit heartbeat 120"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cognibrew

  qdrant:
    image: qdrant/qdrant:v1.17
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333" # HTTP
      - "6334:6334" # gRPC
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/localhost/6334'"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cognibrew

volumes:
  rabbitmq_data:
  qdrant_data:

networks:
  cognibrew:
    driver: bridge
    name: cognibrew
