services:
  tmp-frontend:
    build: ./services/tmp-frontend
    container_name: cognibrew-tmp-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      tmp-backend:
        condition: service_started
    networks:
      - cognibrew

  tmp-backend:
    image: teetinnapop/actions:cognibrew-inference-server-latest
    platform: linux/amd64
    container_name: cognibrew-tmp-backend
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${INF_LOG_LEVEL:-INFO}
      API_ENROLL_URL: ${API_ENROLL_URL:-http://localhost:8000/api/v1/gateway/enroll}
      MODEL_FRAMEWORK: ${INF_MODEL_FRAMEWORK:-insightface}
      MODEL_NAME: ${INF_MODEL_NAME:-buffalo_sc}
    networks:
      - cognibrew

networks:
  cognibrew:
    driver: bridge
